apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-05-09T05:29:01Z"
  labels:
    app: model-server-pod
  name: model-server-pod
spec:
  containers:
  - env:
    - name: TERM
      value: xterm
    image: quay.io/rbrhssa/pfms-ocp:latest
    name: model-server
    ports:
    - containerPort: 2024
      hostPort: 2024
    - containerPort: 80
      hostPort: 9000
    securityContext:
      runAsNonRoot: true
    stdin: true
    tty: true
