name: Build and push bootc image for ChRIS

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Extract latest tag
      id: extract_tag
      run: |
        latest_tag=$(git describe --abbrev=0 --tags)
        echo "::set-output name=latest_tag::$latest_tag"

    - name: Increment tag
      id: increment_tag
      run: |
        latest_tag="${{ steps.extract_tag.outputs.latest_tag }}"
        IFS='.' read -r major minor <<< "$latest_tag"
        incremented_minor=$((minor + 1))
        new_tag="$major.$incremented_minor"
        echo "::set-output name=new_tag::$new_tag"

    - name: Install Podman
      run: |
        sudo apt update
        sudo apt install -y podman

    - name: Build and push Podman image
      env:
        QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
        QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
        QUAY_URL: ${{ secrets.QUAY_URL }}
        QUAY_REPOSITORY: ${{ secrets.QUAY_REPOSITORY }}
      run: |
        new_tag="${{ steps.increment_tag.outputs.new_tag }}"
        IMAGE_NAME=$QUAY_URL/$QUAY_REPOSITORY/chbox:$new_tag
        podman build -t $IMAGE_NAME .
        podman login -u $QUAY_USERNAME -p $QUAY_PASSWORD $QUAY_URL
        podman push $IMAGE_NAME
