name: Build and Push Podman Image

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Podman
      run: |
        sudo apt update
        sudo apt install -y podman

    - name: Build and push Podman image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        QUAY_URL: ${{ secrets.QUAY_URL }}
        QUAY_REPOSITORY: ${{ secrets.QUAY_REPOSITORY }}
      run: |
        COMMIT_HASH=$(git rev-parse --short HEAD)
        TAG=$(echo $GITHUB_REF | sed 's|.*/||')
        IMAGE_NAME=$QUAY_URL/$QUAY_REPOSITORY/chbox:$TAG
        podman build -t $IMAGE_NAME .
        podman login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $QUAY_URL
        podman tag $IMAGE_NAME $QUAY_URL/$QUAY_REPOSITORY/chbox:$COMMIT_HASH
        podman push $IMAGE_NAME
        podman push $QUAY_URL/$QUAY_REPOSITORY/chbox:$COMMIT_HASH
